### ISSUE TITLE
input=textarea的column开启搜索时，搜索输入框是textarea而不是input

### ISSUE THREAD

**Issue by ansonhorse** [nmxiaowei/avue#200]
### Avue版本
2.4.0

### 重现
```
{
  type: 'textarea',
  label: '备注',
  prop: 'memo',
  search: true,
  span: 24
}
```

### 实际效果
![image](https://user-images.githubusercontent.com/7548142/76684425-f4dba280-6646-11ea-94ee-169cc7265618.png)

### 预期效果
可以自动做一个转换，即如果column的type为`textarea`，那么在渲染它的搜索项时，使用`type=input`。
如果是我没哪个地方没用对，还请告知，谢谢！

### 临时解决
覆盖搜索栏里textarea的样式
```scss
.avue-crud-search {
  .el-input--small {
    textarea {
      height: 32px !important;
      min-height: 32px !important;
      resize: none;
      overflow: hidden;
    }
  }
  .el-input--mini {
    textarea {
      height: 28px !important;
      min-height: 28px !important;
      resize: none;
      overflow: hidden;
    }
  }
}
```
